name: Release

on:
  push:
    branches:
      - main
    paths:
      - src/**

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'

      - name: Set up Git user
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Install dependencies
        run: npm ci

      - name: Test
        run: |
          npm run lint
          npm test -- --collectCoverage

      - name: Publish
        run: |
          npm run release
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}

      - name: Generate documentation
        run: npm run docs

      - name: Move coverage into docs
        run: mv coverage/lcov-report docs/coverage

      - name: Deploy documentation
        uses: rdarida/simple-github-pages-deploy-action@v1
        with:
          git-user: 'github-actions[bot]'
          git-email: 'github-actions[bot]@users.noreply.github.com'
          git-base-folder: 'docs'
          commit-message: 'Automatic deploy'
