name: Test

on:
  push:
    branches:
      - main
    paths:
      - src/**
      - tests/**

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1

      - run: |
          npm ci
          npm run lint
          npm test
